# Generated by Django 4.2.1 on 2023-05-29 05:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_alter_video_description_alter_video_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Proxy Video',
                'verbose_name_plural': 'Proxy Videos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('video.video',),
        ),
        migrations.AddField(
            model_name='video',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=220),
            preserve_default=False,
        ),
    ]
